# Site settings
title: StevenDao.
author: Steven Dao
email: Steven.Dao@alum.utoronto.ca
description: >
  Making a change, One step at a time. <br>
  Always a work in progress.
baseurl: "/"
url: "https://stevendao.github.io"
github_username:  StevenDao
permalink: "/:title"
# Build settings
markdown: kramdown
gems: [jekyll-paginate]
# Paginate Settings
paginate: 3
paginate_path: "/projects/:num/"
sass:
    sass_dir: _sass
    style: compressed