# Site settings
title: StevenDao.
author: Steven Dao
email: steven.dao@alum.utoronto.ca
baseurl: "/"
url: "https://stevendao.github.io"
work_year: 2014
work_title: "Software Engineer"
github_username: StevenDao
url_linkedin: https://www.linkedin.com/in/daosteven/
url_github: https://github.com/StevenDao
url_instagram: https://www.instagram.com/okinadaikon/
permalink: "/:title"
# Build settingsß
markdown: kramdown
gems: [jekyll-paginate]
# Paginate Settings
paginate: 3
paginate_path: "/projects/:num/"
sass:
    sass_dir: _sass
    style: compressed