# Site settings
title: Steven Dao
author: Steven Dao
email: Steven.Dao@alum.utoronto.ca
description: >
  This is still a work in progress! <br>
  Making a change, one step at a time!
baseurl: ""
url: "https://stevendao.github.io"
github_username:  StevenDao
permalink: "/:title"
# Build settings
markdown: kramdown
gems: [jekyll-paginate]
# Paginate Settings
paginate: 5
paginate_path: "/projects/:num/"

sass:
    sass_dir: _sass
    style: compressed